### ISSUE TITLE
Take Redirect URI as env variable

### ISSUE THREAD

**Issue by ofpiyush** [verloop/accuaman#18]
https://github.com/verloop/accuaman/blob/bd146a7/src/server/server.go#L60

**Comment by avinassh** [comment]
You mean `BASE_UI_URL`? 

https://github.com/verloop/accuaman/blob/bd146a7/src/server/server.go#L65

There are two redirect URLs. One which is used in OAuth and one which is used after OAuth, which redirects to UI

**Comment by ofpiyush** [comment]
Aah, the naming.

`BASE_URL` -> the FQDN+path of the customer's namespace.
eg: `apollomunich.verloop.io`

`REDIRECT_URL` -> relative path from BASE_URL where you redirect after a successful authentication.

Your Google's Oauth Redirect URL would then become `BASE_URL+/oauth2callback/google`

The second is the URL where you redirect after a successful auth. `BASE_URL+REDIRECT_URL`

This `REDIRECT_URL` can be hardcoded/given a sane default for our use case.

**Comment by avinassh** [comment]
yeah, I agree these are bad names. I will fix these 😅

**Comment by avinassh** [comment]
@ofpiyush this is also not needed for this week?

**Comment by ofpiyush** [comment]
@avinassh yes not for this week
