### ISSUE TITLE
google oauth final step

### ISSUE THREAD

**Issue by ofpiyush** [verloop/accuaman#21]
Encrypt verloop's access token with a shared secret with RC and attach that value to the URL.

Stop setting the cookie.

**Comment by avinassh** [comment]
So... which encryption algorithm you recommend? AES 128 will do? The whole thing will be within HTTPS anyways.

**Comment by ofpiyush** [comment]
@dalchand plis to decide with @avinassh

**Comment by avinassh** [comment]
AES 256
